language: node_js
node_js: node
deploy: 
  provider: heroku
  edge: true
  api_key:
    secure: 8bff6e67-45fb-49d8-a1a8-2266acb85838
  app: mysterious-savannah-61301
  on:
    repo: fucata55/node-shopping-list-integration-tests
