language: node_js
node_js: node
deploy: 
  provider: heroku
  edge: true
  api_key:
    secure: 488ad498-8a97-485b-b6f0-c6f7384ba1fe
  app: mysterious-savannah-61301
  on:
    repo: fucata55/node-shopping-list-integration-tests
